######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 30 16:39:35 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += arg.h data.h guiimpl.h plotimpl.h popsize.h rng.h
FORMS += gui.ui plot.ui
SOURCES += arg.cpp data.cpp guiimpl.cpp plotimpl.cpp popsize.cpp simmlst.cpp
